#!/usr/bin/env bash
# The file path Field Separator) is set to :
IFS=':'
while read -r username password user_id group_id user_info home_directory shell
do
printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$username" "$group_id" "$home_directory" "$shell" "$user_id" "$password" "$user_info"
done < /etc/passwd
