#!/usr/bin/env bash
# Script that display Best School in 10 lines


count=1

while [ $count -le 10 ]; do

  if [ $count -eq 4 ]; then

    echo "bad luck"

  elif [ $count -eq 8 ]; then

    echo "good luck"

  else

    echo "Best School"

  fi

  count=$((count + 1))

done
