#!/usr/bin/env bash
# Script that displays many things
Nvar="/var/run/myscript.pid"
echo $$ > Nvar
while true;
do
	echo "To infinity and beyond"	
done
trap 'echo "I hate the kill command"; rm "$script"; kill' SIGTERM SIGQUIT
